apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    ipfailover: ipfailover
  name: ipfailover
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      ipfailover: ipfailover
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        ipfailover: ipfailover
    spec:
      containers:
      - env:
        - name: OPENSHIFT_HA_CHECK_INTERVAL
          value: "2"
        - name: OPENSHIFT_HA_CHECK_SCRIPT
        - name: OPENSHIFT_HA_CONFIG_NAME
          value: ipfailover
        - name: OPENSHIFT_HA_IPTABLES_CHAIN
          value: INPUT
        - name: OPENSHIFT_HA_MONITOR_PORT
          value: "8080"
        - name: OPENSHIFT_HA_NETWORK_INTERFACE
        - name: OPENSHIFT_HA_NOTIFY_SCRIPT
        - name: OPENSHIFT_HA_PREEMPTION
          value: nopreempt
        - name: OPENSHIFT_HA_REPLICA_COUNT
          value: "1"
        - name: OPENSHIFT_HA_USE_UNICAST
          value: "false"
        - name: OPENSHIFT_HA_VIP_GROUPS
          value: "0"
        - name: OPENSHIFT_HA_VIRTUAL_IPS
          value: 192.168.1.9
        - name: OPENSHIFT_HA_VRRP_ID_OFFSET
          value: "0"
        image: registry.redhat.io/openshift3/ose-keepalived-ipfailover:v3.11.200
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - pgrep
            - keepalived
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: ipfailover-keepalived
        ports:
        - containerPort: 63000
          hostPort: 63000
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ipfailover
      serviceAccountName: ipfailover
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
